### ISSUE TITLE
Add decimal

### ISSUE THREAD

**Issue by gcadoret** [tyugaev/jquery-number-divider#1]
Hi Mikhail, 

and thank for sharing your code. 

do you thing it's possible to add decimal at the end ? for example : 

5 000 000,45

i made this custom delimiterRegExp : "/[\s]/g" 

but it's not displaying very well : 

54 546 546 546 .44

and i want this display 

54 546 546 546,44 with only 2 decimals at the end. 

thanks you ! :+1:

**Comment by mtyugaev** [comment]
Hi, i made this plugin long time ago and now i have no idea how it can be improved, sorry :)

**Comment by gcadoret** [comment]
Hello, ok not problem :) i found another solution :)
